from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from datetime import datetime


SEVERITY_COLORS = {
    "High": colors.HexColor("#dc2626"),
    "Medium": colors.HexColor("#ca8a04"),
    "Low": colors.HexColor("#16a34a"),
    "Info": colors.HexColor("#6b7280"),
}


def generate_pdf_report(url, score, findings, output_path):
    """Builds a PDF security report from scan results and saves it to output_path."""
    doc = SimpleDocTemplate(output_path, pagesize=letter,
                             topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("TitleStyle", parent=styles["Title"], fontSize=20)
    heading_style = ParagraphStyle("HeadingStyle", parent=styles["Heading2"], spaceBefore=14)
    body_style = ParagraphStyle("BodyStyle", parent=styles["BodyText"], fontSize=10, leading=14)

    elements = []

    # Header
    elements.append(Paragraph("Web Security Analysis Report", title_style))
    elements.append(Spacer(1, 6))
    elements.append(Paragraph(f"<b>Target:</b> {url}", body_style))
    elements.append(Paragraph(f"<b>Scan date:</b> {datetime.now().strftime('%Y-%m-%d %H:%M')}", body_style))
    elements.append(Paragraph(f"<b>Security Score:</b> {score}/100", body_style))
    elements.append(Spacer(1, 16))

    # Summary table
    elements.append(Paragraph("Findings Summary", heading_style))
    table_data = [["Finding", "Severity", "Category", "Confidence"]]
    for f in findings:
        table_data.append([f["header"], f["severity"], f["category"], f.get("confidence", "High")])

    table = Table(table_data, colWidths=[2.2 * inch, 0.9 * inch, 1.6 * inch, 0.9 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eeeeee")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9f9f9")]),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 20))

    # Detailed findings
    elements.append(Paragraph("Detailed Findings", heading_style))
    for f in findings:
        sev_color = SEVERITY_COLORS.get(f["severity"], colors.black)
        elements.append(Spacer(1, 10))
        elements.append(Paragraph(
            f'<font color="{sev_color.hexval()}"><b>{f["header"]} — {f["severity"]}</b></font>',
            body_style
        ))
        explanation_html = f["explanation"].replace("\n", "<br/>")
        elements.append(Paragraph(explanation_html, body_style))

    # Disclaimer
    elements.append(Spacer(1, 24))
    elements.append(Paragraph(
        "<i>This report was generated by an automated tool performing passive security checks. "
        "It does not constitute a full penetration test or professional security audit.</i>",
        body_style
    ))

    doc.build(elements)